version: 2
jobs:
  test:
    working_directory: ~/build
    docker:
      - image: docker
    steps:
      - run: echo  "test job"

  build:
    working_directory: ~/build
    docker:
      - image: docker
    steps:
      - run: echo  "build job"


workflows:
  version: 2
  pimline_tests:
    jobs:
      - test
      - build: 
          requires:
            - test
          
   
    
